var lyrics = [
  ["Hidin'", "and", "hidin'", "each", "other"],
  ["Smile", "and", "cover", "and", "cover"],
  ["Sell", "it", "and", "buy", "it", "like", "water"],
  ["When", "did", "we", "normalize", "danger?"],
  ["Walk", "out", "the", "dark", "forest"], 
  ["I", "gotta", "go", "back", "to", "you", "every", "time"],
  ["If", "you", "feel", "the", "courage"], 
  ["yeah,", "go", "'head", "and", "dial'"],
  ["It's", "so", "bad,", "bad,", "bad"],
  ["Tell", "me", "what's", "killing", "you"],
  ["It", "ain't", "cool,", "cool,", "cool"],
  ["Can't", "recognize", "us", "anymore"],
  ["To", "the", "ocean,", "we", "don't", "back", "down"],
  ["Only", "we", "can", "find", "a", "way", "out"],
  ["Where", "is", "the", "love?"],
  ["We", "can", "find", "the", "love"],
  ["S-O-S-O-S-O,", "right", "now"],
  ["Every", "day,", "we're", "fightin'"],
  ["A", "silent", "war", "we", "never", "wanted"],
  ["Come", "on,", "right", "now"],
  ["People", "keep", "on", "dyin'"],
  ["When", "the", "world", "is", "killin'", "you,", "yeah"],
  ["Just", "shoot", "the", "S-O-S,", "S-O-S"],
  ["Please", "tell", "me,", "S-O-S,", "S-O-S"],
  ["Don't", "worry", "I'll", "be", "waitin'", "here"],
  ["all", "the", "time", "'cause", "I'm", "your", "friend"]
];